<div class="org-details">

    <div class="container container-fluid detail-banner-wrapper">
        <div class="detail-banner" style="background-image: url('https://ucarecdn.com/f93709b6-ba67-482b-9d12-9f79d79a582e/-/preview/1140x280/')">
            <div class="logo">
                <img src="https://ucarecdn.com/b2c479ad-5768-4975-801d-db903ab54713/-/preview/120x120/">
            </div>
        </div>
        <div class="controls">

             <span class="status">
                <a href="https://" target="_blank"></a>
            </span>


            <div class="handbid-share-bar">
                <a class="icon facebook" href="https://www.facebook.com/sharer.php?u=http%3A%2F%2Fhandbid.loc%2Forganizations%2Fadaptive-adventures%2F" onclick="javascript:window.open(this.href,'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;"></a>

                <a class="icon google-plus" href="https://plus.google.com/share?url=http%3A%2F%2Fhandbid.loc%2Forganizations%2Fadaptive-adventures%2F" onclick="javascript:window.open(this.href,'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;">g+</a>

                <a class="icon twitter" href="https://www.twitter.com/share?url=http%3A%2F%2Fhandbid.loc%2Forganizations%2Fadaptive-adventures%2F" onclick="javascript:window.open(this.href,'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;">Tweet</a>

                <a class="icon pinterest" href="https://pinterest.com/pin/create/button/?url=http%3A%2F%2Fhandbid.loc%2Forganizations%2Fadaptive-adventures%2F&amp;description=Handbid+Auction" onclick="javascript:window.open(this.href,'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;">Share on Pinterest</a>
                <a class="icon email" href="mailto:?subject=Handbid+Auction&amp;body=http%3A%2F%2Fhandbid.loc%2Forganizations%2Fadaptive-adventures%2F" title="Share by Email">Email</a>
            </div>
        </div>
    </div>

    <ul class="slider-nav col-md-12 auto-open" data-slider-nav-id="org-details">
        <li>
            <a data-slider-nav-key="auctions">Auctions</a>
        </li>
        <li>
            <a data-slider-nav-key="map" class="map-holder-item">Contact Us</a>
        </li>
    </ul>

    <div class="slider-content" data-slider-nav-id="org-details">


        <div class="container container-fluid" data-slider-nav-key="auctions">

            <div class="section-nav auction-list">
                Auctions <a href="/organizations/">| Organizations</a>
            </div>

            <div class="row sort-bar auction-item-list" style="transition: none; margin-bottom: 15px;">

                <div class="category-cover-cheating"></div>

                <div class="col-md-6 col-xs-6 fancy-search-wrapper">

                    <form class="fancy-search" method="get">
                        <button type="submit">Search Auctions</button>
                        <input class="query categories-query" type="search" name="search" placeholder="Search Auctions" value="">
                        <a class="reset" href="#" style="display: none">X</a>
                    </form>

                </div>
            </div>

            <div class="sort-bar auction-list">

                <div class="col-md-3">

                </div>

                <div class="col-md-6 legend">
                    <a href="/organizations/adaptive-adventures/?auction_list=current" class="current selected"><span class="box"></span>current</a>
                    <a href="/organizations/adaptive-adventures/?auction_list=open" class="open"><span class="box"></span>Open</a>
                    <a href="/organizations/adaptive-adventures/?auction_list=presale" class="presale"><span class="box"></span>Presale</a>
                    <a href="/organizations/adaptive-adventures/?auction_list=preview" class="preview"><span class="box"></span>Preview</a>
                    <a href="/organizations/adaptive-adventures/?auction_list=closed" class="closed"><span class="box"></span>Closed</a>
                </div>

                <div class="col-md-3 select-wrapper">

                </div>
            </div>

            <div class="row simple-box-row auctions">

                <h3 class="no-results">No Auctions Found</h3>


            </div>
        </div>


        <div class="details-map" data-slider-nav-key="map" data-address="Colorado	Illinois 1315 Nelson St.   Unit 1  Lakewood Colorado 80215">


            <div id="large-map"></div>
            <div id="small-map"></div>
            <div style="display: none" id="map-marker-content">
                <div class="overflow">
                    <div class="row">
                        <div class="col-md-6 iw-label">Location</div>
                        <div class="col-md-6">Adaptive Adventures</div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 iw-label">Email</div>
                        <div class="col-md-6"><a target="_blank" href="mailto:jimmy@adaptiveadventures.org">jimmy@adaptiveadventures.org</a></div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 iw-label">Address</div>
                        <div class="col-md-6">Colorado	Illinois 1315 Nelson St.   Unit 1 <br>Lakewood, COLORADO 80215</div>
                    </div>
                    <div class="row submit">
                        <a class="pink-button get-directions" onclick="getDirections()" href="#">Get Directions</a>
                    </div>
                </div>
            </div>
        </div>


    </div>



</div>