<div class="handbid-form row" ng-if="(vm.auction && (vm.current_auth_screen == 'confirm-purchase'))">
    <div class="col-xs-12">

        <div class="purchase-container confirmed-tickets-container loading-tickets-container"></div>

        <div class="row">
            <div class="form-group col-md-3 col-xs-6 buttons left-aligned">
                <button class="btn btn-gray" id="hb-confirm-tickets-back"><span>Back</span></button>
            </div>
            <div class="form-group col-md-3 col-md-offset-6 col-xs-6 buttons right-aligned">
                <button class="btn" id="hb-confirm-tickets-pay"><span>Purchase</span></button>
            </div>
        </div>
    </div>
</div>