<div class="handbid-form row" ng-if="(vm.auction && (vm.current_auth_screen == 'process-error'))">
    <div class="col-xs-12 handbid-form-area">

        <div class="process-container">
            <p class="process-message">
                We attempted to charge
                <span class="payment-sum">
                                <span class="handbidAuctionCurrency" title="{{ vm.auction.currencyCode }}"><?php echo $currencySymbol; ?></span>
                                <span class="tickets-full-price">50</span>
                            </span>
                <span class="smaller-text">to the card <span data-card-number>xxxx-xxxx-xxxx-4903</span> and got this error</span>
            </p>

            <p class="process-message-error">
                card declined
            </p>

            <button class="pink-solid-button" id="hb-ticket-payment-error-card">Add new card</button>
        </div>

        <div class="row">
            <div class="form-group col-md-3 col-xs-6 buttons left-aligned">
                <button class="btn btn-gray"  id="hb-ticket-payment-error-back"><span>Back</span></button>
            </div>
        </div>
    </div>

</div>