<div class="handbid-form row" ng-if="(vm.current_auth_screen == 'process-success')">
    <div class="col-xs-12 handbid-form-area">

        <div class="process-container process-success-container">
            <div class="hide-if-no-tickets" style="display: none">
                <p class="process-message">
                    <span class="smaller-text">You are all set for</span>
                    <span data-auction-item>{{ vm.auction.name }} Tickets?</span>
                </p>
                <h4>Your tickets</h4>

                <div class="tickets-section result-tickets-container"></div>
            </div>

            <h4 class="block-only-for-auction">Auction information</h4>

            <div class="auction-info-section">
                <div class="row">
                    <div class="col-sm-4 reg-info-block-paddle block-only-for-auction">
                        <h5>You have been registered with</h5>
                        <p>Paddle # <span class="paddle-number reg-paddle-number">176</span></p>
                    </div>
                    <div class="col-sm-4 block-only-for-auction">
                        <h5>Want to bid from your smartphone?</h5>
                        <p>Get setup on my phone</p>
                        <a href="#" class="btn loading-span-button" id="hb-text-a-link">
                            <span>Text me a link</span>
                        </a>
                    </div>
                    <div class="col-sm-4 block-for-all-pages">
                        <h5>Want to bid right now?</h5>
                        <p>Bid on my computer</p>
                        <a href="#" class="btn start-bidding-button"><span>Start bidding</span></a>
                    </div>
                </div>
            </div>

        </div>

    </div>
</div>