<div class="handbid-form row" ng-if="(vm.auction && (vm.current_auth_screen == 'purchase-tickets'))">
    <div class="col-xs-12 handbid-form-area tickets-modal tickets-on-register">

        <div class="row">
            <h5 class="col-xs-12 upper-tickets-text">
                Selected
            </h5>
            <h4 class="col-xs-12 upper-summary">
                <span class="upper-tickets-count" data-handbid-tickets-quantity>0</span>
                Items for
                <span class="handbidAuctionCurrency" title="{{ vm.auction.currencyCode }}"><?php echo $currencySymbol; ?></span>
                <span class="upper-tickets-count" data-handbid-tickets-total>0</span>
            </h4>
            <div class="col-xs-12">
                <div class="tickets-container loading-tickets-container purchase-container"></div>
            </div>
        </div>

        <div class="row">
            <div class="form-group col-md-3 col-xs-6 buttons left-aligned">
                <button type="submit" class="btn signup btn-gray" id="hb-purchase-tickets-back"
                        ng-click="vm.setCurrentAuthScreen('process-success')"
                ><span>SKIP</span></button>
            </div>
            <div class="form-group col-md-3 col-md-offset-6 col-xs-6 buttons right-aligned">
                <button class="btn" disabled="disabled" id="hb-purchase-tickets-next"><span>Purchase</span></button>
            </div>
        </div>
    </div>
</div>