<h3 class="no-results" ng-hide="vm.auction">{{ (vm.initialization) ? 'Loading...' : 'No Auction Found' }}</h3>

<div class="auction-details {{vm.auction.status}}" ng-show="vm.auction"
     data-handbid-auction-guid="{{vm.auction.auctionGuid}}">
    <div class="container container-fluid detail-banner-wrapper">
        <div class="detail-banner"
             style="background-image: url('{{vm.auction.bannerImage}}-/preview/1140x280/')">
            <div class="logo">
                <img ng-src="{{ vm.auction.imageUrl }}-/preview/120x120/">
            </div>
        </div>
        <div class="controls">

            @include('main.auction._parts.share_bar')
            <span class="buttons">
            <a href="#" class="button pink-button register" data-handbid-connect="" style="display: none;">Register</a>


<a class="button pink-button handbid-modal-link purchase-tickets" data-handbid-credit-cards-need=""
   data-handbid-modal-key="tickets-form" data-handbid-tickets="">Buy Tickets</a>


@include('main.auction._parts.tickets_popup')

                <span class="status">
                Status<span class="status-box"></span><span class="status-label">{{vm.auction.status}}</span>
            </span>
            </span>


        </div>
    </div>


    <ul class="slider-nav col-md-12 auto-open" data-slider-nav-id="auction-details">
        <li>
            <a data-slider-nav-key="items" class="active-slide">Items</a>
        </li>
        <li>
            <a data-slider-nav-key="description">Auction Information</a>
        </li>
    </ul>
    <div class="slider-content" data-slider-nav-id="auction-details">

        <div class="container container-fluid active-slide" data-slider-nav-key="items">
            <div class="row">

                <div class="sticky sticky-for-sort-bar">

                    <div class="sort-bar auction-item-list">

                        <div class="category-cover-cheating"></div>

                        <div class="col-md-6 col-xs-6 fancy-search-wrapper">

                            <form class="fancy-search" method="get">
                                <button type="button">Search Items</button>
                                <input class="query" ng-model="vm.items_search" placeholder="Search items">
                                <a class="reset" ng-click="vm.clearItemsSearch()"
                                   ng-show="(vm.items_search != '')">X</a>
                            </form>

                        </div>
                        <div class="col-md-2 col-xs-2 sort-label">Sort By:</div>
                        <div class="col-md-4 col-xs-4 select-wrapper">
                            <select name="sort" ng-model="vm.items_sorting_type" ng-change="vm.changeItemsOrdering()">
                                <option ng-repeat="option in vm.getFiltersOrdering()"
                                        ng-selected="(vm.items_sorting_type == option.value)"
                                        value="{{option.value}}">{{option.title}}</option>
                            </select>

                        </div>
                    </div>

                    <div class="clear"></div>

                    <div class="mobile-filters">
                        <select name="mobile-sort" ng-model="vm.items_sorting_type" ng-change="vm.changeItemsOrdering()">
                            <option ng-repeat="option in vm.getFiltersOrdering()"
                                    ng-selected="(vm.items_sorting_type == option.value)"
                                    value="{{option.value}}">{{option.title}}</option>
                        </select>

                        <select name="mobile-type" ng-model="vm.items_type">
                            <option ng-repeat="option in vm.getFiltersByType(true)"
                                    ng-selected="(vm.items_type == option.value)"
                                    value="{{option.value}}">{{option.title}}</option>
                        </select>

                        <select name="mobile-category" ng-model="vm.items_category">
                            <option ng-repeat="option in vm.getFiltersByCategories(true)"
                                    ng-selected="(vm.items_category == option.value)"
                                    value="{{option.value}}">{{option.title}}</option>
                        </select>

                    </div>

                </div>

            </div>

            <div class="row">

                <div class="col-md-2 col-sm-3 col-xs-12 sticky filter-wrapper" data-sticky-margin-top="65">

                    <div class="filters">

                        <div class="section" data-section="type">
                            <h4>Items</h4>
                            <ul class="by-item-type">

                                <li ng-repeat="option in vm.getFiltersByType(false)"
                                    ng-class="{'selected' : (vm.items_type == option.value)}"
                                        value="{{option.value}}">
                                    <a ng-click="vm.changeItemsType(option.value)">{{option.title}}</a>
                                </li>
                            </ul>
                        </div>

                        <div class="section" data-section="category" style="display: block">
                            <h4>Categories</h4>
                            <ul class="by-category">

                                <li ng-repeat="option in vm.getFiltersByCategories(false)"
                                    ng-class="{'selected' : (vm.items_category == option.value)}"
                                    value="{{option.value}}">
                                    <a ng-click="vm.changeItemsCategory(option.value)">{{option.title}}</a>
                                </li>

<!--                                <li ng-class="{'selected' : (vm.items_category == 'all')}">-->
<!--                                    <a ng-click="vm.changeItemsCategory('all')">All (<span>{{ vm.items.length }}</span>)</a>-->
<!--                                </li>-->
<!---->
<!---->
<!--                                <li ng-repeat="category in vm.categories"-->
<!--                                    ng-class="{'selected' : (vm.items_category == category.id)}"-->
<!--                                    data-legacy-category-id="{{ category.id }}">-->
<!--                                    <a ng-click="vm.changeItemsCategory(category.id)">{{ category.name }} ({{ category.items.length }})</a>-->
<!--                                </li>-->

                            </ul>
                        </div>

                    </div>


                </div>
                <div class="col-md-10 col-sm-9 col-xs-12">


                    <div class="row simple-box-row item-list isotope" style="position: relative;">

                        <div ng-show="vm.displayed_items.length"
                             ng-repeat="current_item in vm.displayed_items | orderBy : vm.order_by : vm.order_reverse">
                            <div handbid-item-box="current_item" auction="vm.auction"></div>
                        </div>


                        <h3 class="message-no-isotope-results" ng-hide="vm.displayed_items.length">Sorry! We couldn't
                            find any
                            matching items. Search
                            again!</h3>

                        <div class="sizer col-md-4 col-sm-6 col-xs-12"></div>

                    </div>

                </div>
            </div>
        </div>

        <div class="container container-fluid big-content" data-slider-nav-key="description">
            {{ vm.auction.description }}
        </div>


    </div>
</div>