<div class="receipts-list-area" data-nonce="35ab7dbf8b">
    <ul class="simple-list">
        <li class="row receiptRow margin-bottom preview                " 1=""
            data-receipt-block-id="24620" data-receipt-of-auction="274"
            data-receipt-block-guid="56aad0dc-6ef1-44bc-ba87-2946aa2f1922"
            data-receipt-total="700.00">
            <div class="col-md-10">
                <h4 class="invoice-title margin-bottom">Diana Demo Auction -
                    Invoice </h4>
            </div>
            <div class="col-md-2">
                <a class="cta-link" data-toggle-invoice-link="24620">View</a>
            </div>
            <div class="col-md-12 invoice-details-container"
                 style="display: none;">

                <table class="table  table-receipt-summary ">
                    <tbody>
                    <tr>
                        <th scope="row">Auction Total</th>
                        <td class="format-money">$<em>700.00</em></td>
                    </tr>
                    <tr>
                        <th scope="row">Purchase Total</th>
                        <td class="format-money">$<em>0.00</em></td>
                    </tr>
                    <tr class="receipt-total">
                        <th scope="row">Subtotal</th>
                        <td class="format-money">$<em>700.00</em></td>
                    </tr>
                    <tr>
                        <th scope="row">Premium (Rate 0.0%)</th>
                        <td class="format-money">$<em>0.00</em></td>
                    </tr>
                    <tr class="receipt-due">
                        <th scope="row" class="total">TOTAL</th>
                        <td class="receipt-total format-money text-red"
                            data-attribute="grandTotal">$<em>700.00</em></td>
                    </tr>
                    </tbody>
                </table>
                <div class="col-xs-12 margin-bottom">
                    <div class="col-xs-6 col-md-3">
                        <a class="buy-now green-solid-button receipt-action-button col-md-12 loading-span-button"
                           onclick="handbidMain.sendInvoice('24620','121212@gmail.com', false)"><span>Email Receipt</span></a>
                    </div>
                    <div class="col-xs-6 col-md-3">
                        <a class="buy-now green-solid-button receipt-action-button col-md-12 loading-span-button"
                           onclick="handbidMain.sendInvoice('24620','121212', true)"><span>Text Receipt</span></a>
                    </div>
                </div>
                <div class="unpaidControls">


                    <div
                        class="col-md-12  margin-bottom receipt-payment-block hideIfNoCCAllowed">
                        <div class="col-md-6">
                            <select class="select-payment-card col-md-12"
                                    style="">
                                <option data-option-val="34121" value="34121"
                                        selected="selected">Some (xxxx xxxx xxxx
                                    4242)
                                </option>
                            </select>
                        </div>
                        <div class="col-md-5">
                            <a class="buy-now green-solid-button receipt-action-button make-payment-button col-md-12 loading-span-button"
                               data-auction-id="274" data-receipt-id="24620"
                               data-make-payment-nonce="000f0ca904"
                               data-handbid-credit-cards-need=""><span>Make Payment</span></a>
                        </div>
                    </div>

                    <div
                        class="col-md-12  margin-bottom receipt-payment-block showIfNoCCAllowed">
                        <div class="col-md-12">
                            <h4>Payments have been disabled through the
                                site.<br>Contact the auction manager to pay.
                            </h4>
                        </div>
                    </div>
                </div>

                <div class="col-md-12 margin-bottom paidControls"
                     style=" display:none; ">
                    <div
                        class="col-xs-12 col-md-6 col-xs-offset-0 col-md-offset-3">
                        <a class="buy-now green-solid-button receipt-action-button col-md-12 loading-span-button"><span>Paid In Full</span></a>
                    </div>
                </div>


                <div class="col-md-12">
                    <a class="cta-link margin-bottom"
                       data-toggle-invoice-more-link="24620">More
                        Details</a>
                </div>

                <div
                    class="item-1-col row col-md-12 invoice-more-details-container"
                    style="display: none;">

                    <div class="receipt">
                        <h4>Auction Items (<span class="format-money">$<em>700.00</em></span>)
                        </h4>

                        <div id="w0" class="grid-view">
                            <table class="table table-striped table-bordered">
                                <thead>
                                <tr>
                                    <th>Item Code</th>
                                    <th>Item Name</th>
                                    <th>Market Value</th>
                                    <th>Category</th>
                                    <th>Bid</th>
                                    <th>Tax</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr data-key="27923">
                                    <td>E-09</td>
                                    <td>Apple Watch</td>
                                    <td class="format-money">$<em>750.00</em>
                                    </td>
                                    <td>Electronics</td>
                                    <td class="format-money">$<em>700.00</em>
                                    </td>
                                    <td class="format-money">$<em>0.00</em></td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>
            </div>
        </li>
        <li class="row receiptRow margin-bottom preview                " 1=""
            data-receipt-block-id="24625" data-receipt-of-auction="7"
            data-receipt-block-guid="96e6b6ac-1dca-4dc0-9782-6dac87f957e3"
            data-receipt-total="377.50">
            <div class="col-md-10">
                <h4 class="invoice-title margin-bottom">Handbid Demo Auction -
                    Invoice </h4>
            </div>
            <div class="col-md-2">
                <a class="cta-link" data-toggle-invoice-link="24625">View</a>
            </div>
            <div class="col-md-12 invoice-details-container"
                 style="display: none;">

                <table class="table  table-receipt-summary ">
                    <tbody>
                    <tr>
                        <th scope="row">Auction Total</th>
                        <td class="format-money">$<em>0.00</em></td>
                    </tr>
                    <tr>
                        <th scope="row">Purchase Total</th>
                        <td class="format-money">$<em>365.00</em></td>
                    </tr>
                    <tr class="receipt-total">
                        <th scope="row">Subtotal</th>
                        <td class="format-money">$<em>365.00</em></td>
                    </tr>
                    <tr>
                        <th scope="row">Premium (Rate 0.0%)</th>
                        <td class="format-money">$<em>0.00</em></td>
                    </tr>
                    <tr>
                        <th scope="row">Item Tax</th>
                        <td class="format-money">$<em>12.50</em></td>
                    </tr>
                    <tr class="receipt-due">
                        <th scope="row" class="total">TOTAL</th>
                        <td class="receipt-total format-money text-red"
                            data-attribute="grandTotal">$<em>377.50</em></td>
                    </tr>
                    </tbody>
                </table>
                <div class="col-xs-12 margin-bottom">
                    <div class="col-xs-6 col-md-3">
                        <a class="buy-now green-solid-button receipt-action-button col-md-12 loading-span-button"
                           onclick="handbidMain.sendInvoice('24625','121212@gmail.com', false)"><span>Email Receipt</span></a>
                    </div>
                    <div class="col-xs-6 col-md-3">
                        <a class="buy-now green-solid-button receipt-action-button col-md-12 loading-span-button"
                           onclick="handbidMain.sendInvoice('24625','121212', true)"><span>Text Receipt</span></a>
                    </div>
                </div>
                <div class="unpaidControls">


                    <div
                        class="col-md-12  margin-bottom receipt-payment-block hideIfNoCCAllowed">
                        <div class="col-md-6">
                            <select class="select-payment-card col-md-12"
                                    style="">
                                <option data-option-val="34121" value="34121"
                                        selected="selected">Some (xxxx xxxx xxxx
                                    4242)
                                </option>
                            </select>
                        </div>
                        <div class="col-md-5">
                            <a class="buy-now green-solid-button receipt-action-button make-payment-button col-md-12 loading-span-button"
                               data-auction-id="7" data-receipt-id="24625"
                               data-make-payment-nonce="000f0ca904"
                               data-handbid-credit-cards-need=""
                               data-require-address-to-pay=""><span>Make Payment</span></a>
                        </div>
                    </div>

                    <div
                        class="col-md-12  margin-bottom receipt-payment-block showIfNoCCAllowed">
                        <div class="col-md-12">
                            <h4>Payments have been disabled through the
                                site.<br>Contact the auction manager to pay.
                            </h4>
                        </div>
                    </div>
                </div>

                <div class="col-md-12 margin-bottom paidControls"
                     style=" display:none; ">
                    <div
                        class="col-xs-12 col-md-6 col-xs-offset-0 col-md-offset-3">
                        <a class="buy-now green-solid-button receipt-action-button col-md-12 loading-span-button"><span>Paid In Full</span></a>
                    </div>
                </div>


                <div class="col-md-12">
                    <a class="cta-link margin-bottom"
                       data-toggle-invoice-more-link="24625">More
                        Details</a>
                </div>

                <div
                    class="item-1-col row col-md-12 invoice-more-details-container"
                    style="display: none;">

                    <div class="receipt">
                        <h4>Purchases (<span
                                class="format-money">$<em>365.00</em></span>)
                        </h4>

                        <div id="w1" class="grid-view">
                            <table class="table table-striped table-bordered">
                                <thead>
                                <tr>
                                    <th>Item Code</th>
                                    <th>Item Name</th>
                                    <th>Quantity</th>
                                    <th>Unit Price</th>
                                    <th>ItemTax</th>
                                    <th>Total</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr data-key="358">
                                    <td>1000</td>
                                    <td>Drink Ticket</td>
                                    <td>3</td>
                                    <td class="format-money">$<em>1.00</em></td>
                                    <td class="format-money">$<em>0.00</em></td>
                                    <td class="format-money">$<em>3.00</em></td>
                                </tr>
                                <tr data-key="42125">
                                    <td>#42125</td>
                                    <td>Early Bird Family Ticket</td>
                                    <td>2</td>
                                    <td class="format-money">$<em>75.00</em>
                                    </td>
                                    <td class="format-money">$<em>0.00</em></td>
                                    <td class="format-money">$<em>150.00</em>
                                    </td>
                                </tr>
                                <tr data-key="12434">
                                    <td>12434</td>
                                    <td>Broncos Football</td>
                                    <td>1</td>
                                    <td class="format-money">$<em>125.00</em>
                                    </td>
                                    <td class="format-money">$<em>12.50</em>
                                    </td>
                                    <td class="format-money">$<em>125.00</em>
                                    </td>
                                </tr>
                                <tr data-key="34732">
                                    <td>#34732</td>
                                    <td>Child Admission</td>
                                    <td>1</td>
                                    <td class="format-money">$<em>10.00</em>
                                    </td>
                                    <td class="format-money">$<em>0.00</em></td>
                                    <td class="format-money">$<em>10.00</em>
                                    </td>
                                </tr>
                                <tr data-key="358">
                                    <td>1000</td>
                                    <td>Drink Ticket</td>
                                    <td>2</td>
                                    <td class="format-money">$<em>1.00</em></td>
                                    <td class="format-money">$<em>0.00</em></td>
                                    <td class="format-money">$<em>2.00</em></td>
                                </tr>
                                <tr data-key="42125">
                                    <td>#42125</td>
                                    <td>Early Bird Family Ticket</td>
                                    <td>1</td>
                                    <td class="format-money">$<em>75.00</em>
                                    </td>
                                    <td class="format-money">$<em>0.00</em></td>
                                    <td class="format-money">$<em>75.00</em>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>
            </div>
        </li>
    </ul>
</div>