<div class="bidder-info-container credit-card">

    <ul class="simple-list bid-history" ng-if="(profile.creditCards.length > 0)">
        <li class="row" ng-repeat="card in profile.creditCards">
            <div class="col-md-3">
                <h4>Name</h4>
                {{ card.nameOnCard }}
            </div>
            <div class="col-md-3">
                <h4>Card Number</h4>
                xxxx xxxx xxxx {{ card.lastFour }}
            </div>
            <div class="col-md-3">
                <h4>Exp. Date</h4>
                {{ card.expMonth }}/{{ card.expYear }}
            </div>
            <div class="col-md-3">
                <a class="button pink-solid-button loading-span-button"
                   ng-class="{'active' : card.isRemoving}"
                   ng-click="tools.removeCreditCard(card)"
                >
                    <em>Delete</em>
                </a>
            </div>
        </li>
    </ul>

    <div class="row no-results-row" ng-if="(profile.creditCards.length == 0)">

        <p style="text-align: left;">Note: Not all auctions use credit cards</p>

        <label class="no-results">
            You have no cards on file.
        </label>
    </div>

    <div class="row">

        <a class="button green-solid-button handbid-modal-link credit-card-form-link"
           handbid-modal-link="credit-card-form">Add Credit
            Card</a>

    </div>

    @include('directives.profile.details.credit-cards-modal')

</div>