<div class="bidder-info-container credit-card">

    <ul class="simple-list bid-history">
        <li class="row" data-handbid-card-row="34121">
            <div class="col-md-3">
                <h4>Name</h4>
                Some
            </div>
            <div class="col-md-3">
                <h4>Card Number</h4>
                xxxx xxxx xxxx 4242
            </div>
            <div class="col-md-3">
                <h4>Exp. Date</h4>
                12/2020
            </div>
            <div class="col-md-3">
                <a class="button pink-solid-button loading-span-button"
                   data-handbid-delete-credit-card="34121"><em>Delete</em></a>
            </div>
        </li>
    </ul>

    <input type="hidden" id="deleteCardNonce" value="d6ef692d2b">

    <!--<div id="credit-card-required-banner">-->
    <!--    -->
    <div class="row">


        <a class="button green-solid-button handbid-modal-link credit-card-form-link"
           data-handbid-modal-key="credit-card-form">Add Credit
            Card</a>


    </div>
    <div class="handbid-modal modal fade credit-card-form-modal" tabindex="-1"
         role="dialog" data-handbid-modal-key="credit-card-form">
        <div class="modal-dialog">
            <h3>Add Credit Card</h3>
            <a href="#" class="modal-close" data-dismiss="modal"
               aria-label="Close">×</a>

            <form id="creditcard-template" class="creditcard-template"
                  action="http://handbid.loc/wp-admin/admin-post.php"
                  method="post" enctype="multipart/form-data">
                <div class="credit-card-status"></div>
                <div class="creditcard">
                    <div class="cc-section">
                        <label>Name on Card</label>
                        <input type="text" name="nameOnCard" value=""
                               class="ccNameOnCard checkout-input checkout-name"
                               placeholder="Name on Card">
                    </div>
                    <div class="cc-section">
                        <label>Expiration</label>
                        <input type="text" name="expMonth"
                               class="checkout-input checkout-exp"
                               data-stripe="exp-month" value=""
                               placeholder="MM">
                        <input type="text" name="expYear"
                               class="checkout-input checkout-exp"
                               data-stripe="exp-year" value=""
                               placeholder="YYYY">
                    </div>
                    <br>

                    <div class="cc-section bottom-row">
                        <label>Card Number</label>
                        <input type="text" name="cardNum"
                               class="checkout-input checkout-card"
                               placeholder="Credit Card Number"
                               data-stripe="number">
                    </div>
                    <div class="cc-section bottom-row cvc-section">
                        <label>CVC</label>

                        <input type="text" name="cvc"
                               class="checkout-input checkout-cvc"
                               placeholder="CVC" data-stripe="cvc">

                        <span class="cvc-help" data-tooltip-wrapper="">
                        <a class="cvc-info" data-tooltip-activate="" title="cvc">?</a>
                        <div class="simple-tooltip-content" data-tooltip-content="">On most cards, the 3-digit security code is on the back, to the right of the signature. On American Express cards, the 4-digit security code is on the front, to the top-right of the card number.</div>
                    </span>

                    </div>
                </div>
                <input type="submit" class="green-solid-button submit-cc-button"
                       value="submit">
                <input type="hidden" name="nonce" value="b4f2f62283"
                       id="hb-credit-card-nonce">
                <input type="hidden" name="action"
                       value="handbid_ajax_add_credit_card">
                <input type="hidden" name="redirect"
                       value="http://handbid.loc/auctions/handbid-demo-auction/">

            </form>
        </div>
    </div>

    <!--    --><!--</div>-->
</div>