<div class="messages-list-area" data-nonce="65fdf9036c">
    <ul class="simple-list">
        <li class="row message-row purchase messages-part-0" style="">
            <div class="col-md-1">
                <span class="message-status message-status-purchase"></span>
            </div>
            <div class="col-md-4 message-date"><b>August 02, 2016 </b>
                <span>11:48am</span>
            </div>
            <div class="col-md-7">
                You've added item #42125 Early Bird Family Ticket to your
                invoice!

            </div>
        </li>
        <li class="row message-row purchase messages-part-0" style="">
            <div class="col-md-1">
                <span class="message-status message-status-purchase"></span>
            </div>
            <div class="col-md-4 message-date"><b>August 02, 2016 </b>
                <span>11:48am</span>
            </div>
            <div class="col-md-7">
                You've added item 1000 Drink Ticket to your invoice!

            </div>
        </li>
        <li class="row message-row purchase messages-part-0" style="">
            <div class="col-md-1">
                <span class="message-status message-status-purchase"></span>
            </div>
            <div class="col-md-4 message-date"><b>August 02, 2016 </b>
                <span>11:48am</span>
            </div>
            <div class="col-md-7">
                You've added item #34732 Child Admission to your invoice!

            </div>
        </li>
        <li class="row message-row purchase messages-part-0" style="">
            <div class="col-md-1">
                <span class="message-status message-status-purchase"></span>
            </div>
            <div class="col-md-4 message-date"><b>August 02, 2016 </b>
                <span>11:10am</span>
            </div>
            <div class="col-md-7">
                You've added item 12434 Broncos Football to your invoice!

            </div>
        </li>
        <li class="row message-row was_winning messages-part-0" style="">
            <div class="col-md-1">
                <span class="message-status message-status-was_winning"></span>
            </div>
            <div class="col-md-4 message-date"><b>August 02, 2016 </b>
                <span>10:28am</span>
            </div>
            <div class="col-md-7">
                You are already winning #207 Dining With Kids
            </div>
        </li>
        <li class="row message-row was_winning messages-part-1"
            style=" display:none; ">
            <div class="col-md-1">
                <span class="message-status message-status-was_winning"></span>
            </div>
            <div class="col-md-4 message-date"><b>August 02, 2016 </b>
                <span>10:00am</span>
            </div>
            <div class="col-md-7">
                You are already winning #207 Dining With Kids
            </div>
        </li>
        <li class="row message-row was_winning messages-part-1"
            style=" display:none; ">
            <div class="col-md-1">
                <span class="message-status message-status-was_winning"></span>
            </div>
            <div class="col-md-4 message-date"><b>August 02, 2016 </b>
                <span>10:00am</span>
            </div>
            <div class="col-md-7">
                You are already winning #207 Dining With Kids
            </div>
        </li>
        <li class="row message-row winning messages-part-1"
            style=" display:none; ">
            <div class="col-md-1">
                <span class="message-status message-status-winning"></span>
            </div>
            <div class="col-md-4 message-date"><b>August 02, 2016 </b>
                <span>10:00am</span>
            </div>
            <div class="col-md-7">
                You're winning Item Dining With Kids(207) at $500
            </div>
        </li>
        <li class="row message-row purchase messages-part-1"
            style=" display:none; ">
            <div class="col-md-1">
                <span class="message-status message-status-purchase"></span>
            </div>
            <div class="col-md-4 message-date"><b>August 02, 2016 </b>
                <span>7:26am</span>
            </div>
            <div class="col-md-7">
                You've added item #42125 Early Bird Family Ticket to your
                invoice!

            </div>
        </li>
        <li class="row message-row purchase messages-part-1"
            style=" display:none; ">
            <div class="col-md-1">
                <span class="message-status message-status-purchase"></span>
            </div>
            <div class="col-md-4 message-date"><b>August 02, 2016 </b>
                <span>7:26am</span>
            </div>
            <div class="col-md-7">
                You've added item 1000 Drink Ticket to your invoice!

            </div>
        </li>
    </ul>
    <button class="btn pull-left green-button load-more-messages"
            data-current-chunk="0" data-chunks-count="1">More
    </button>
    <button class="btn pull-right green-button load-less-messages"
            style="display: none">Collapse
    </button>
</div>