<div class="receipts-list-area">
    <ul class="simple-list">
        <li class="row receiptRow margin-bottom "
            ng-repeat="receipt in receipts track by $index"
            ng-class="{'open' : receipt.paid, 'preview' : !receipt.paid}">
            <div class="col-md-10">
                <h4 class="invoice-title margin-bottom">{{ receipt.name }}</h4>
            </div>
            <div class="col-md-2">
                <a class="cta-link" data-toggle-invoice-link="24620">View</a>
            </div>
            <div class="col-md-12 invoice-details-container"
                 style="display: none;">

                <table class="table  table-receipt-summary ">
                    <tbody>
                    <tr>
                        <th scope="row">Auction Total</th>
                        <td class="format-money">$<em>700.00</em></td>
                    </tr>
                    <tr>
                        <th scope="row">Purchase Total</th>
                        <td class="format-money">$<em>0.00</em></td>
                    </tr>
                    <tr class="receipt-total">
                        <th scope="row">Subtotal</th>
                        <td class="format-money">$<em>700.00</em></td>
                    </tr>
                    <tr>
                        <th scope="row">Premium (Rate 0.0%)</th>
                        <td class="format-money">$<em>0.00</em></td>
                    </tr>
                    <tr class="receipt-due">
                        <th scope="row" class="total">TOTAL</th>
                        <td class="receipt-total format-money text-red"
                            data-attribute="grandTotal">$<em>700.00</em></td>
                    </tr>
                    </tbody>
                </table>
                <div class="col-xs-12 margin-bottom">
                    <div class="col-xs-6 col-md-3">
                        <a class="buy-now green-solid-button receipt-action-button col-md-12 loading-span-button"
                           onclick="handbidMain.sendInvoice('24620','121212@gmail.com', false)"><span>Email Receipt</span></a>
                    </div>
                    <div class="col-xs-6 col-md-3">
                        <a class="buy-now green-solid-button receipt-action-button col-md-12 loading-span-button"
                           onclick="handbidMain.sendInvoice('24620','121212', true)"><span>Text Receipt</span></a>
                    </div>
                </div>
                <div class="unpaidControls">


                    <div
                        class="col-md-12  margin-bottom receipt-payment-block hideIfNoCCAllowed">
                        <div class="col-md-6">
                            <select class="select-payment-card col-md-12"
                                    style="">
                                <option data-option-val="34121" value="34121"
                                        selected="selected">Some (xxxx xxxx xxxx
                                    4242)
                                </option>
                            </select>
                        </div>
                        <div class="col-md-5">
                            <a class="buy-now green-solid-button receipt-action-button make-payment-button col-md-12 loading-span-button"
                               data-auction-id="274" data-receipt-id="24620"
                               data-make-payment-nonce="000f0ca904"
                               data-handbid-credit-cards-need=""><span>Make Payment</span></a>
                        </div>
                    </div>

                    <div
                        class="col-md-12  margin-bottom receipt-payment-block showIfNoCCAllowed">
                        <div class="col-md-12">
                            <h4>Payments have been disabled through the
                                site.<br>Contact the auction manager to pay.
                            </h4>
                        </div>
                    </div>
                </div>

                <div class="col-md-12 margin-bottom paidControls"
                     style=" display:none; ">
                    <div
                        class="col-xs-12 col-md-6 col-xs-offset-0 col-md-offset-3">
                        <a class="buy-now green-solid-button receipt-action-button col-md-12 loading-span-button"><span>Paid In Full</span></a>
                    </div>
                </div>


                <div class="col-md-12">
                    <a class="cta-link margin-bottom"
                       data-toggle-invoice-more-link="24620">More
                        Details</a>
                </div>

                <div
                    class="item-1-col row col-md-12 invoice-more-details-container"
                    style="display: none;">

                    <div class="receipt">
                        <h4>Auction Items (<span class="format-money">$<em>700.00</em></span>)
                        </h4>

                        <div id="w0" class="grid-view">
                            <table class="table table-striped table-bordered">
                                <thead>
                                <tr>
                                    <th>Item Code</th>
                                    <th>Item Name</th>
                                    <th>Market Value</th>
                                    <th>Category</th>
                                    <th>Bid</th>
                                    <th>Tax</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr data-key="27923">
                                    <td>E-09</td>
                                    <td>Apple Watch</td>
                                    <td class="format-money">$<em>750.00</em>
                                    </td>
                                    <td>Electronics</td>
                                    <td class="format-money">$<em>700.00</em>
                                    </td>
                                    <td class="format-money">$<em>0.00</em></td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>
            </div>
        </li>
    </ul>
    <pre>{{receipts | json}}</pre>
</div>