<form class="edit-profile">
    <ul class="simple-list">
        <li class="row">
            <div class="col-md-12">
                <input type="text" ng-model="tools.form_profile.alias" placeholder="Alias" title="Alias">
            </div>
        </li>
        <li class="row">
            <div class="col-md-6">
                <input type="text" ng-model="tools.form_profile.firstName" placeholder="First Name" title="First Name">
            </div>
            <div class="col-md-6">
                <input type="text" ng-model="tools.form_profile.lastName" placeholder="Last Name" title="Last Name">
            </div>
        </li>
        <li class="row">
            <div class="col-md-12">
                <span title="Email" style="text-transform: uppercase;">{{ tools.form_profile.email }}</span>
            </div>
        </li>
        <li class="row">
            <div class="col-md-4">
                <select title="Country" ng-model="tools.form_profile.userAddressCountryId" class="col-md-12">
                    <option ng-repeat="option in tools.countries_and_provinces"
                            ng-selected="(tools.form_profile.userAddressCountryId == option.id)"
                            value="{{option.id}}">{{option.name}}</option>
                </select>
            </div>
            <div class="col-md-8">
                <input type="tel" ng-model="tools.form_profile.userCellPhone" placeholder="Cell Phone" title="Cell Phone">
            </div>
        </li>
        <li class="row">
            <div class="col-md-6">
                <input type="password" name="password" placeholder="Password"
                       title="Password" id="profileNewPassword">
            </div>
            <div class="col-md-6">
                <input type="password" name="password2"
                       placeholder="Confirm Password" title="Confirm Password"
                       id="profileNewPasswordConfirm">
            </div>
        </li>
        <li class="row">
            <div class="col-md-8">
                <input type="text" id="shippingAddress" handbid-google-autocomplete
                       ng-model="tools.form_profile.shippingAddress" placeholder="Shipping Address"
                       title="Shipping Address">
            </div>
        </li>
        <li class="row">
            <div class="col-md-5">
                <span
                style="text-transform: uppercase; padding: 6px 0px; display: block;">Bid confirmations Enabled: </span>
            </div>
            <div class="col-md-7">
                <select ng-model="tools.form_profile.bidConfirmationsEnabled" title="Bid Confirmations"
                        class="col-md-12">
                    <option value="yes" selected="selected">Yes</option>
                    <option value="no">No</option>
                </select>
            </div>
        </li>
    </ul>
    <div class="row">
        <div class="col-md-12">
            <button class="button green-solid-button loading-span-button"
                   ng-class="{'active' : tools.is_updating_profile}"
                   ng-click="tryToUpdateProfile()"
                   id="updateUserProfile"><span>Submit</span></button>
        </div>
    </div>
</form>