<form class="edit-profile" action="http://handbid.loc/wp-admin/admin-post.php"
      method="post" enctype="multipart/form-data">
    <input type="hidden" id="payInvoiceID" name="payInvoiceID" value="">
    <ul class="simple-list">
        <li class="row">
            <div class="col-md-12">
                <input type="text" ng-model="profile.alias" placeholder="Alias" title="Alias">
            </div>
        </li>
        <li class="row">
            <div class="col-md-12">
                <input type="text" ng-model="profile.firstName" placeholder="First Name" title="First Name">
            </div>
        </li>
        <li class="row">
            <div class="col-md-12">
                <input type="text" ng-model="profile.lastName" placeholder="Last Name" title="Last Name">
            </div>
        </li>
        <li class="row">
            <div class="col-md-12">
                <span title="Email" style="text-transform: uppercase;">{{ profile.email }}</span>
            </div>
        </li>
        <li class="row">
            <div class="col-md-4">
                <select id="userAddressCountryId" name="userAddressCountryId"
                        title="Country" data-provinces-nonce="c2a759249d"
                        class="col-md-12">
                    <option value="194">Abkhazia</option>
                    <option value="1">Afghanistan</option>
                    <option value="258">Aland</option>
                    <option value="2">Albania</option>
                    <option value="3">Algeria</option>
                    <option value="238">American Samoa</option>
                    <option value="4">Andorra</option>
                    <option value="5">Angola</option>
                    <option value="223">Anguilla</option>
                    <option value="6">Antigua and Barbuda</option>
                    <option value="7">Argentina</option>
                    <option value="8">Armenia</option>
                    <option value="259">Aruba</option>
                    <option value="262">Ascension</option>
                    <option value="201">Ashmore and Cartier Islands</option>
                    <option value="9">Australia</option>
                    <option value="264">Australian Antarctic Territory</option>
                    <option value="10">Austria</option>
                    <option value="11">Azerbaijan</option>
                    <option value="12">Bahamas, The</option>
                    <option value="13">Bahrain</option>
                    <option value="239">Baker Island</option>
                    <option value="14">Bangladesh</option>
                    <option value="15">Barbados</option>
                    <option value="16">Belarus</option>
                    <option value="17">Belgium</option>
                    <option value="18">Belize</option>
                    <option value="19">Benin</option>
                    <option value="224">Bermuda</option>
                    <option value="20">Bhutan</option>
                    <option value="21">Bolivia</option>
                    <option value="22">Bosnia and Herzegovina</option>
                    <option value="23">Botswana</option>
                    <option value="216">Bouvet Island</option>
                    <option value="24">Brazil</option>
                    <option value="268">British Antarctic Territory</option>
                    <option value="225">British Indian Ocean Territory</option>
                    <option value="226">British Sovereign Base Areas</option>
                    <option value="227">British Virgin Islands</option>
                    <option value="25">Brunei</option>
                    <option value="26">Bulgaria</option>
                    <option value="27">Burkina Faso</option>
                    <option value="28">Burundi</option>
                    <option value="29">Cambodia</option>
                    <option value="30">Cameroon</option>
                    <option value="31">Canada</option>
                    <option value="32">Cape Verde</option>
                    <option value="228">Cayman Islands</option>
                    <option value="33">Central African Republic</option>
                    <option value="34">Chad</option>
                    <option value="35">Chile</option>
                    <option value="36">China, People's Republic of</option>
                    <option value="195">China, Republic of (Taiwan)</option>
                    <option value="202">Christmas Island</option>
                    <option value="215">Clipperton Island</option>
                    <option value="203">Cocos (Keeling) Islands</option>
                    <option value="37">Colombia</option>
                    <option value="38">Comoros</option>
                    <option value="40">Congo, (Congo ? Brazzaville)</option>
                    <option value="39">Congo, (Congo ? Kinshasa)</option>
                    <option value="217">Cook Islands</option>
                    <option value="204">Coral Sea Islands</option>
                    <option value="41">Costa Rica</option>
                    <option value="42">Cote d'Ivoire (Ivory Coast)</option>
                    <option value="43">Croatia</option>
                    <option value="44">Cuba</option>
                    <option value="45">Cyprus</option>
                    <option value="46">Czech Republic</option>
                    <option value="47">Denmark</option>
                    <option value="48">Djibouti</option>
                    <option value="49">Dominica</option>
                    <option value="50">Dominican Republic</option>
                    <option value="51">Ecuador</option>
                    <option value="52">Egypt</option>
                    <option value="53">El Salvador</option>
                    <option value="54">Equatorial Guinea</option>
                    <option value="55">Eritrea</option>
                    <option value="56">Estonia</option>
                    <option value="57">Ethiopia</option>
                    <option value="229">Falkland Islands (Islas Malvinas)
                    </option>
                    <option value="252">Faroe Islands</option>
                    <option value="58">Fiji</option>
                    <option value="59">Finland</option>
                    <option value="60">France</option>
                    <option value="254">French Guiana</option>
                    <option value="208">French Polynesia</option>
                    <option value="214">French Southern and Antarctic Lands
                    </option>
                    <option value="61">Gabon</option>
                    <option value="62">Gambia, The</option>
                    <option value="63">Georgia</option>
                    <option value="64">Germany</option>
                    <option value="65">Ghana</option>
                    <option value="230">Gibraltar</option>
                    <option value="66">Greece</option>
                    <option value="253">Greenland</option>
                    <option value="67">Grenada</option>
                    <option value="255">Guadeloupe</option>
                    <option value="240">Guam</option>
                    <option value="68">Guatemala</option>
                    <option value="220">Guernsey</option>
                    <option value="69">Guinea</option>
                    <option value="70">Guinea-Bissau</option>
                    <option value="71">Guyana</option>
                    <option value="72">Haiti</option>
                    <option value="205">Heard Island and McDonald Islands
                    </option>
                    <option value="73">Honduras</option>
                    <option value="250">Hong Kong</option>
                    <option value="241">Howland Island</option>
                    <option value="74">Hungary</option>
                    <option value="75">Iceland</option>
                    <option value="76">India</option>
                    <option value="77">Indonesia</option>
                    <option value="78">Iran</option>
                    <option value="79">Iraq</option>
                    <option value="80">Ireland</option>
                    <option value="221">Isle of Man</option>
                    <option value="81">Israel</option>
                    <option value="82">Italy</option>
                    <option value="83">Jamaica</option>
                    <option value="84">Japan</option>
                    <option value="242">Jarvis Island</option>
                    <option value="222">Jersey</option>
                    <option value="243">Johnston Atoll</option>
                    <option value="85">Jordan</option>
                    <option value="86">Kazakhstan</option>
                    <option value="87">Kenya</option>
                    <option value="244">Kingman Reef</option>
                    <option value="88">Kiribati</option>
                    <option value="89">Korea, North</option>
                    <option value="90">Korea, South</option>
                    <option value="91">Kuwait</option>
                    <option value="92">Kyrgyzstan</option>
                    <option value="93">Laos</option>
                    <option value="94">Latvia</option>
                    <option value="95">Lebanon</option>
                    <option value="96">Lesotho</option>
                    <option value="97">Liberia</option>
                    <option value="98">Libya</option>
                    <option value="99">Liechtenstein</option>
                    <option value="100">Lithuania</option>
                    <option value="101">Luxembourg</option>
                    <option value="251">Macau</option>
                    <option value="102">Macedonia</option>
                    <option value="103">Madagascar</option>
                    <option value="104">Malawi</option>
                    <option value="105">Malaysia</option>
                    <option value="106">Maldives</option>
                    <option value="107">Mali</option>
                    <option value="108">Malta</option>
                    <option value="109">Marshall Islands</option>
                    <option value="256">Martinique</option>
                    <option value="110">Mauritania</option>
                    <option value="111">Mauritius</option>
                    <option value="209">Mayotte</option>
                    <option value="112">Mexico</option>
                    <option value="113">Micronesia</option>
                    <option value="245">Midway Islands</option>
                    <option value="114">Moldova</option>
                    <option value="115">Monaco</option>
                    <option value="116">Mongolia</option>
                    <option value="117">Montenegro</option>
                    <option value="231">Montserrat</option>
                    <option value="118">Morocco</option>
                    <option value="119">Mozambique</option>
                    <option value="120">Myanmar (Burma)</option>
                    <option value="196">Nagorno-Karabakh</option>
                    <option value="121">Namibia</option>
                    <option value="122">Nauru</option>
                    <option value="246">Navassa Island</option>
                    <option value="123">Nepal</option>
                    <option value="124">Netherlands</option>
                    <option value="260">Netherlands Antilles</option>
                    <option value="207">New Caledonia</option>
                    <option value="125">New Zealand</option>
                    <option value="126">Nicaragua</option>
                    <option value="127">Niger</option>
                    <option value="128">Nigeria</option>
                    <option value="218">Niue</option>
                    <option value="206">Norfolk Island</option>
                    <option value="197">Northern Cyprus</option>
                    <option value="236">Northern Mariana Islands</option>
                    <option value="129">Norway</option>
                    <option value="130">Oman</option>
                    <option value="131">Pakistan</option>
                    <option value="132">Palau</option>
                    <option value="247">Palmyra Atoll</option>
                    <option value="133">Panama</option>
                    <option value="134">Papua New Guinea</option>
                    <option value="135">Paraguay</option>
                    <option value="136">Peru</option>
                    <option value="266">Peter I Island</option>
                    <option value="137">Philippines</option>
                    <option value="232">Pitcairn Islands</option>
                    <option value="138">Poland</option>
                    <option value="139">Portugal</option>
                    <option value="198">Pridnestrovie (Transnistria)</option>
                    <option value="237">Puerto Rico</option>
                    <option value="140">Qatar</option>
                    <option value="267">Queen Maud Land</option>
                    <option value="257">Reunion</option>
                    <option value="141">Romania</option>
                    <option value="265">Ross Dependency</option>
                    <option value="142">Russia</option>
                    <option value="143">Rwanda</option>
                    <option value="210">Saint Barthelemy</option>
                    <option value="233">Saint Helena</option>
                    <option value="144">Saint Kitts and Nevis</option>
                    <option value="145">Saint Lucia</option>
                    <option value="211">Saint Martin</option>
                    <option value="212">Saint Pierre and Miquelon</option>
                    <option value="146">Saint Vincent and the Grenadines
                    </option>
                    <option value="147">Samoa</option>
                    <option value="148">San Marino</option>
                    <option value="149">Sao Tome and Principe</option>
                    <option value="150">Saudi Arabia</option>
                    <option value="151">Senegal</option>
                    <option value="152">Serbia</option>
                    <option value="153">Seychelles</option>
                    <option value="154">Sierra Leone</option>
                    <option value="155">Singapore</option>
                    <option value="156">Slovakia</option>
                    <option value="157">Slovenia</option>
                    <option value="158">Solomon Islands</option>
                    <option value="159">Somalia</option>
                    <option value="199">Somaliland</option>
                    <option value="160">South Africa</option>
                    <option value="234">South Georgia &amp; South Sandwich
                        Islands
                    </option>
                    <option value="200">South Ossetia</option>
                    <option value="161">Spain</option>
                    <option value="162">Sri Lanka</option>
                    <option value="163">Sudan</option>
                    <option value="164">Suriname</option>
                    <option value="261">Svalbard</option>
                    <option value="165">Swaziland</option>
                    <option value="166">Sweden</option>
                    <option value="167">Switzerland</option>
                    <option value="168">Syria</option>
                    <option value="169">Tajikistan</option>
                    <option value="170">Tanzania</option>
                    <option value="171">Thailand</option>
                    <option value="172">Timor-Leste (East Timor)</option>
                    <option value="173">Togo</option>
                    <option value="219">Tokelau</option>
                    <option value="174">Tonga</option>
                    <option value="175">Trinidad and Tobago</option>
                    <option value="263">Tristan da Cunha</option>
                    <option value="176">Tunisia</option>
                    <option value="177">Turkey</option>
                    <option value="178">Turkmenistan</option>
                    <option value="235">Turks and Caicos Islands</option>
                    <option value="179">Tuvalu</option>
                    <option value="248">U.S. Virgin Islands</option>
                    <option value="180">Uganda</option>
                    <option value="181">Ukraine</option>
                    <option value="182">United Arab Emirates</option>
                    <option value="183">United Kingdom</option>
                    <option value="184" selected="selected">United States
                    </option>
                    <option value="185">Uruguay</option>
                    <option value="186">Uzbekistan</option>
                    <option value="187">Vanuatu</option>
                    <option value="188">Vatican City</option>
                    <option value="189">Venezuela</option>
                    <option value="190">Vietnam</option>
                    <option value="249">Wake Island</option>
                    <option value="213">Wallis and Futuna</option>
                    <option value="191">Yemen</option>
                    <option value="192">Zambia</option>
                    <option value="193">Zimbabwe</option>
                </select>
            </div>
            <div class="col-md-8">
                <input type="tel" ng-model="profile.userCellPhone" placeholder="Cell Phone" title="Cell Phone">
            </div>
        </li>
        <li class="row provincesRow" style="">
            <div class="col-md-12">
                <select id="userAddressProvinceId" name="userAddressProvinceId"
                        title="Province" class="col-md-12">
                    <option value="2">Alabama</option>
                    <option value="1">Alaska</option>
                    <option value="4">Arizona</option>
                    <option value="3">Arkansas</option>
                    <option value="5">California</option>
                    <option value="6" selected="selected">Colorado</option>
                    <option value="7">Connecticut</option>
                    <option value="9">Delaware</option>
                    <option value="8">District of Columbia</option>
                    <option value="10">Florida</option>
                    <option value="11">Georgia</option>
                    <option value="12">Hawaii</option>
                    <option value="14">Idaho</option>
                    <option value="15">Illinois</option>
                    <option value="16">Indiana</option>
                    <option value="13">Iowa</option>
                    <option value="17">Kansas</option>
                    <option value="18">Kentucky</option>
                    <option value="19">Louisiana</option>
                    <option value="22">Maine</option>
                    <option value="21">Maryland</option>
                    <option value="20">Massachusetts</option>
                    <option value="23">Michigan</option>
                    <option value="24">Minnesota</option>
                    <option value="26">Mississippi</option>
                    <option value="25">Missouri</option>
                    <option value="27">Montana</option>
                    <option value="30">Nebraska</option>
                    <option value="34">Nevada</option>
                    <option value="31">New Hampshire</option>
                    <option value="32">New Jersey</option>
                    <option value="33">New Mexico</option>
                    <option value="35">New York</option>
                    <option value="28">North Carolina</option>
                    <option value="29">North Dakota</option>
                    <option value="36">Ohio</option>
                    <option value="37">Oklahoma</option>
                    <option value="38">Oregon</option>
                    <option value="39">Pennsylvania</option>
                    <option value="40">Rhode Island</option>
                    <option value="41">South Carolina</option>
                    <option value="42">South Dakota</option>
                    <option value="43">Tennessee</option>
                    <option value="44">Texas</option>
                    <option value="45">Utah</option>
                    <option value="47">Vermont</option>
                    <option value="46">Virginia</option>
                    <option value="48">Washington</option>
                    <option value="50">West Virginia</option>
                    <option value="49">Wisconsin</option>
                    <option value="51">Wyoming</option>
                </select>
                <input type="hidden" id="provincesCountByCountry"
                       data-current-country="0" data-provinces-9="9"
                       data-provinces-31="13" data-provinces-125="16"
                       data-provinces-183="4" data-provinces-184="51">
            </div>
        </li>
        <li class="row">
            <div class="col-md-12">
                <input type="password" name="password" placeholder="Password"
                       title="Password" id="profileNewPassword">
            </div>
        </li>
        <li class="row">
            <div class="col-md-12">
                <input type="password" name="password2"
                       placeholder="Confirm Password" title="Confirm Password"
                       id="profileNewPasswordConfirm">
            </div>
        </li>
        <li class="row">
            <div class="col-md-8">
                <input type="text" ng-model="profile.shippingAddress" placeholder="Shipping Address" title="Shipping Address">
            </div>
            <div class="col-md-4">
                <input class="button btn-small green-solid-button"
                       value="Toggle Map" id="update_profile_location_map"
                       onclick="handbidMain.toggleProfileLocationMap();">
            </div>
        </li>
        <li id="profile-location-map-container" class="row"
            style="display:none;">
            <div id="profile-location-map"
                 style="width: 100%; height: 300px;"></div>
        </li>

        <li class="row">
            <div class="col-md-5">
                <span
                style="text-transform: uppercase; padding: 6px 0px; display: block;">Bid confirmations Enabled: </span>
            </div>
            <div class="col-md-7">
                <select ng-model="profile.bidConfirmationsEnabled" title="Bid Confirmations"
                        class="col-md-12">
                    <option value="yes" selected="selected">Yes</option>
                    <option value="no">No</option>
                </select>
            </div>
        </li>
    </ul>
    <div class="row">
        <div class="col-md-12">
            <input class="button green-solid-button" type="submit"
                   value="submit" id="updateUserProfile">
        </div>
    </div>
</form>