<div>
    <div ng-show="(type =='auctions')">
        Find your Handbid auction
    </div>
    <div ng-show="(type =='auction')">
        {{ inst.name }}<span class="under">{{ inst.auctionHeaderTimes }}</span>
    </div>
    <div ng-show="(type =='item')">
        {{ inst.auction.name }}<span class="under">{{ inst.auction.auctionHeaderTimes }}</span>
    </div>
    <div ng-show="(type =='organizations')">
        Find your organization
    </div>
    <div ng-show="(type =='organization')">
        {{ inst.name }}
    </div>
</div>