<ul class="simple-list handbid-list-of-bids handbid-list-of-bids-purchases"
    data-no-items-text="You have not purchased any items.">
    <li class="row" data-dashboard-price="3" data-dashboard-quantity="3"
        data-purchased-item-id="358" data-purchased-item-is-ticket="yes"
        data-purchased-purchase-id="51856">
        <div class="col-md-4 col-xs-4">
            <a href="/auctions/handbid-demo-auction/item/drink-ticket-358"><h4>Drink
                    Ticket</h4></a>
        </div>
        <div class="col-md-4 col-xs-4">
            <h4 class="quantity-total">3 x <span class="handbidAuctionCurrency"
                                                 title="USD">$</span>1</h4>
        </div>
        <div class="col-md-4 col-xs-4">
            <span class="bid-amount winning"><span class="handbidAuctionCurrency" title="USD">$</span><span>3</span></span>
        </div>
    </li>
</ul>