<ul class="simple-list handbid-list-of-bids handbid-list-of-bids-winning"
    data-no-items-text="You are currently not winning any items.">
    <li data-dashboard-price="500" data-winning-item-id="329">
        <h4 class="bid-name">
            <a href="/auctions/handbid-demo-auction/item/dining-with-kids-329">Dining
                With Kids</a>
        </h4>
        <span class="bid-amount winning"><span class="handbidAuctionCurrency"
                                               title="USD">$</span>500</span>
    </li>
</ul>