<h3 class="no-results" ng-hide="vm.item">{{ (vm.initialization) ? 'Loading...' : 'No Item Found' }}</h3>

<div class="item-details item-open items-auction-open"
     ng-show="vm.item"
     data-handbid-item-details-block="63392" data-handbid-item-key="a-picture-is-worth-a-1000-words-63392"
     data-handbid-auction-guid="cf6080a6-72e2-4634-b234-fe3122a1b502" data-item-id="63392" data-item-auction-id="959"
     data-item-is-ticket="no" data-item-is-donation="no">


    <div class="back-to-previous-container">
        <a class="back-to-previous" href="#/auctions/{{ vm.auction.key }}/">
            View All Items
        </a>
    </div>

    <div class="row detail-bar">

        <div class="col-md-7">
            <div class="images">

                <ul ng-if="(vm.item.images.length > 1)" class="slider-nav" data-slider-nav-id="item-image-slider">
                    <a class="slider-arrow prev" data-slider-nav-direction="prev">Previous</a>
                    <a class="slider-arrow next" data-slider-nav-direction="next">Next</a>
                </ul>

                <div ng-if="(vm.item.images.length > 1)" class="slider-content" data-slider-nav-id="item-image-slider"
                     data-slider-progress>
                    <div ng-repeat="(k, v) in vm.item.images" class="image"
                         ng-class="{'active-slide' : (k == 0)}"
                         data-slider-nav-key="item-image-{{ k }}">
                        <div style="background-image: url('{{ v.itemImageUrl }}-/preview/650x500/-/setfill/e7e7e7/-/crop/650x500/center/');
                                background-size: contain;" class="image-holder"></div>
                    </div>
                </div>

                <div ng-if="(vm.item.images.length <= 1)" style="background-image: url('{{ vm.item.images[0].itemImageUrl }}-/preview/650x500/-/setfill/e7e7e7/-/crop/650x500/center/');
                    background-size: contain;" class="image-holder"></div>


                <div ng-if="vm.isBidpadOnly(vm.item)" data-handbid-item-banner="bidpad"
                     class="item-banner live-item" >This item is only
                    available in the live auction.
                </div>
                <div ng-if="vm.isLiveItem(vm.item)" data-handbid-item-banner="live"
                     class="item-banner live-item" >This item is only
                    available in the live auction.
                </div>
                <div ng-if="vm.isItemInLosing(vm.item.id)" data-handbid-item-banner="losing"
                     class="item-banner losing" >You are losing this
                    item.
                </div>
                <div ng-if="vm.isItemInWinning(vm.item.id)"
                     data-handbid-item-banner="winning" class="item-banner winning"
                     >You are winning this item.
                </div>
                <div ng-if="vm.isAlreadySold(vm.item)"
                     data-handbid-item-banner="sold" class="item-banner winning"
                     >This item has already been SOLD!
                </div>
            </div>

            <ul class="slider-nav auto-open" data-slider-nav-id="item-image-slider"
                ng-if="(vm.item.images.length > 1)">
                <a class="circle" ng-repeat="(k, v) in vm.item.images"
                   ng-class="{'active-slide' : (k == 0)}"
                   data-slider-nav-key="item-image-{{ k }}"
                   data-slider-nav-item>Circle</a>
            </ul>
        </div>

        <div class="col-md-5 buttons-and-titles">

            <h2 class="name" >{{ vm.item.name }}</h2>

            <h3 class="category" ng-if="vm.item.categoryName" >{{ vm.item.categoryName }}</h3>

            <ul ng-if="(!vm.isLiveItem(vm.item))" class="horizontal-details not-for-live-auctions row" style="">

                <li ng-if="(vm.isBiddable(vm.item))" class="bids col-md-4 col-xs-3">
                    <em >
                        {{ vm.item.bidCount }}
                    </em>
                    Bids
                </li>
                <li ng-if="(vm.isBiddable(vm.item))" class="increment col-md-4 col-xs-5">
                    <em>
                        <span title="{{ vm.auction.currencyCode }}">{{ vm.auction.currencySymbol }}</span>
                        <span class="incrementSpan">{{ vm.item.bidIncrement }}</span>
                    </em>
                    Increment
                </li>
                <li ng-if="(vm.isBiddable(vm.item))" class="min col-md-4 col-xs-4">
                    <em ng-class="{'itemValueBoxHidden' : vm.isValueHidden(vm.item)}">
                        <span title="{{ vm.auction.currencyCode }}">{{ vm.auction.currencySymbol }}</span>
                        <span>{{ vm.item.value }}</span>
                    </em>
                    Value
                </li>

                <li ng-if="(!vm.isBiddable(vm.item))" class="purchases col-md-4 col-xs-4" >
                    <em ng-class="{'item_hide_sales' : vm.item.hideSales}" >
                        {{ vm.item.quantitySold }}
                    </em>
                    {{ vm.isDonation(vm.item) ? 'Donated' : 'Sold' }}
                </li>
                <li ng-if="(!vm.isBiddable(vm.item))" class="increment col-md-4 col-xs-4">
                    <em>
                        <span title="{{ vm.auction.currencyCode }}">{{ vm.auction.currencySymbol }}</span>
                        <span id="singleItemPrice" >
                            {{ vm.item.buyNowPrice }}
                        </span>
                    </em>
                    Price
                </li>
                <li ng-if="(!vm.isBiddable(vm.item))" class="remaining col-md-4 col-xs-4">
                    <em data-handbid-item-attribute="inventoryRemaining">
                        {{ (vm.item.inventoryRemaining >= 0) ? vm.item.inventoryRemaining : '∞' }}
                    </em>
                    Remaining
                </li>
            </ul>

            @include('main.auction.item._partials.bidding')

            @include('main.auction.item._partials.max_bid_modal')

            @include('main.auction.item._partials.share_bar')

        </div>

    </div>
    <div class="row additional">

        <ul class="slider-nav col-md-12 auto-open" data-slider-nav-id="item-details">

            <li>
                <a data-slider-nav-key="donor" class="active-slide">Donor</a>
            </li>

            <li>
                <a data-slider-nav-key="description" class="">Description</a>
            </li>

            <li>
                <a data-slider-nav-key="bids" class="">History</a>
            </li>

            <li>
                <a data-slider-nav-key="comments" class="">Comments</a>
            </li>
        </ul>
    </div>

    <div class="slider-content" data-slider-nav-id="item-details">

        <div class="additional big-content active-slide" data-slider-nav-key="donor"
             data-handbid-item-attribute="donor">
            {{ vm.item.donor }}
        </div>


        <div class="additional big-content" data-slider-nav-key="description" data-handbid-item-attribute="description">

            <span ng-if="vm.item.showValue">Fair Market Value : {{ vm.item.value }}<br><br></span>
            {{ vm.item.description || "No details provided" }}<br>
            <br>
            <h5>Fine Print</h5>
            {{ vm.item.notables || "Yay! No fine print" }}
        </div>

        <div class="additional big-content bid-history-container-63392" data-slider-nav-key="bids">

            <ul class="simple-list bid-history">

                <li class="row open"
                    ng-if="vm.getBidsCount()"
                    ng-repeat="bid in vm.item.bids"
                    ng-class="{'open' : (bid.status == 'winning'), 'closed' : (bid.status == 'losing')}"
                >
                    <div class="col-md-6">
                        <h4>Bidder Pin</h4>
                        <span>{{ bid.bidderName }}</span>
                    </div>
                    <div class="col-md-6">
                        <span class="bid-amount {{ bid.status }}">
                            <span title="{{ vm.currencyCode }}">{{ vm.currencySymbol }}</span>
                            <span>{{ bid.amount }}</span>
                        </span>
                    </div>
                </li>

                <p class="center-text" ng-if="(vm.getBidsCount() == 0)">No bids yet! You could be the first!</p>
            </ul>

        </div>

        <div class="additional comments" data-slider-nav-key="comments">

            <div class="fb-comments fb_iframe_widget"
                 data-href="http://handbid.loc//auctions/celebration-of-hope/item/a-picture-is-worth-a-1000-words-63392/"
                 data-numposts="5" data-colorscheme="light" fb-xfbml-state="rendered"><span
                    style="height: 180px; width: 550px;"><iframe id="f3542bb990e783c" name="f1a04931e443448"
                                                                 scrolling="no" title="Facebook Social Plugin"
                                                                 class="fb_ltr"
                                                                 src="https://www.facebook.com/plugins/comments.php?api_key=276355612383707&amp;channel_url=http%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter%2Fr%2FLcj5EtQ5qmD.js%3Fversion%3D42%23cb%3Df3361e1b86acd78%26domain%3Dhandbid.loc%26origin%3Dhttp%253A%252F%252Fhandbid.loc%252Ffa4532f0573ebc%26relation%3Dparent.parent&amp;colorscheme=light&amp;href=http%3A%2F%2Fhandbid.loc%2F%2Fauctions%2Fcelebration-of-hope%2Fitem%2Fa-picture-is-worth-a-1000-words-63392%2F&amp;locale=en_US&amp;numposts=5&amp;sdk=joey&amp;skin=light&amp;version=v2.0&amp;width=550"
                                                                 style="border: none; overflow: hidden; height: 180px; width: 550px;"></iframe></span>
            </div>
        </div>

    </div>


</div>