<div class="handbid-share-bar">
    <a class="icon facebook"
       href="https://www.facebook.com/sharer.php?u=http%3A%2F%2Fhandbid.loc%2Fauctions%2Fhandbid-demo-auction%2F"
       onclick="javascript:window.open(this.href,'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;"></a>

    <a class="icon google-plus"
       href="https://plus.google.com/share?url=http%3A%2F%2Fhandbid.loc%2Fauctions%2Fhandbid-demo-auction%2F"
       onclick="javascript:window.open(this.href,'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;">g+</a>

    <a class="icon twitter"
       href="https://www.twitter.com/share?url=http%3A%2F%2Fhandbid.loc%2Fauctions%2Fhandbid-demo-auction%2F"
       onclick="javascript:window.open(this.href,'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;">Tweet</a>

    <a class="icon pinterest"
       href="https://pinterest.com/pin/create/button/?url=http%3A%2F%2Fhandbid.loc%2Fauctions%2Fhandbid-demo-auction%2F&amp;description=Handbid+Auction"
       onclick="javascript:window.open(this.href,'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;">Share
        on Pinterest</a>
    <a class="icon email"
       href="mailto:?subject=Handbid+Auction&amp;body=http%3A%2F%2Fhandbid.loc%2Fauctions%2Fhandbid-demo-auction%2F"
       title="Share by Email">Email</a>
</div>