<div class="handbid-modal modal fade tickets-modal" tabindex="-1" role="dialog" handbid-modal-window="tickets-form"
     data-handbid-tickets="">
    <div class="modal-dialog">
        <h3>Event Tickets / Registration</h3>
        <a href="#" class="modal-close" data-dismiss="modal" aria-label="Close">×</a>


        <div class="tickets-container">

            <div class="row ticket-row" ng-repeat="ticket in vm.items" ng-if="ticket.isTicket"
                 ng-hide="ticket.isHidden"
            >
                <div class="ticket">

                    <div class="col-sm-8 ticket-part-container no-padding-left">

                        <h4 class="ticket-title"><span>{{ticket.name}}</span>
                            &nbsp;&nbsp;<span class="ticket-price">
                                <span title="{{ vm.auction.currencyCode }}">{{ vm.auction.currencySymbol }}</span>
                                <span data-handbid-ticket-buynow="">{{ticket.buyNowPrice}}</span></span>
                        </h4>

                        <p class="ticket-description">{{ticket.description}}</p>


                    </div>
                    <div class="col-sm-4 ticket-part-container no-padding-right tickets-are-sold"
                         ng-show="(ticket.inventoryRemaining == 0)"
                    >
                        <h4>SOLD OUT</h4>
                    </div>

                    <div ng-hide="(ticket.inventoryRemaining == 0)"
                        class="col-xs-6 col-xs-offset-3 col-sm-4 col-sm-offset-0 ticket-part-container no-padding-right tickets-are-available"
                        style="">
                        <div class="col-xs-4 no-padding">
                            <a class="bid-price-toggle bid-down green-button button"
                               ng-class="{'ghosted-out' : (!vm.ticket_counts[ticket.id].quantity)}"
                               ng-click="vm.ticketBuyCountDecrease(ticket)"
                            >-</a>
                        </div>

                        <div class="buy-quantity col-xs-4 no-padding">
                            <span data-handbid-ticket-quantity="">{{vm.ticket_counts[ticket.id].quantity || 0}}</span>
                        </div>

                        <div class="col-xs-4 ticket-quantity-up no-padding">
                            <a class="bid-price-toggle bid-up green-button button"
                               ng-click="vm.ticketBuyCountIncrease(ticket)"
                            >+</a>
                        </div>

                        <div class="col-xs-12 ticket-remaining-inventory-cont no-padding">
                            <span class="remaining-inventory">
                                {{((ticket.inventoryRemaining != -1) ? ticket.inventoryRemaining + " available" : "Unlimited quantity")}}
                            </span>
                        </div>
                    </div>

                </div>
            </div>

        </div>
        <div class="row tickets-footer-row">
            <div class="col-sm-3 col-sm-offset-6">
                <h3 class="total">
                    <span  title="{{ vm.auction.currencyCode }}">{{ vm.auction.currencySymbol }}</span>
                    <span>{{ vm.tickets_price }}</span>
                </h3>
                <h5>Grand Total</h5>
            </div>

            <div class="col-sm-3">
                <a class="button green-solid-button loading-span-button"
                   ng-click="vm.buySelectedTickets()"
                ><span>Add</span></a>
            </div>
        </div>
    </div>
</div>